# This workflow will build gingerspec-starter project with Maven

name: gingerspec-starter pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up JDK 11
      uses: joschi/setup-jdk@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn install -Dmaven.test.skip=true
    - name: Update local archetype catalog
      run: mvn archetype:update-local-catalog && mvn archetype:crawl
    - name: Generating a new project based on local archetype and performing a dry-run
      run: |
        yes | mvn archetype:generate -DarchetypeCatalog=local -DarchetypeGroupId=com.github.privaliatech -DarchetypeArtifactId=gingerspec-starter -DgroupId=eu.vptech -Dversion=1.0-SNAPSHOT -DartifactId=myproject
        cd myproject/
        mvn verify -Dcucumber.execution.dry-run=true


